/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 yellowPepper.glb --types 
*/

import { useGLTF } from '@react-three/drei';
import { ThreeElements } from '@react-three/fiber';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';
type GLTFResult = GLTF & {
  nodes: {
    modelobj: THREE.Mesh
  }
}

export default function YelloPepper(props: ThreeElements["group"]) {
  // Cast the result from useGLTF to unknown, then to our GLTFResult type.
  const { nodes } = useGLTF('https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/yellowPepper.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.modelobj.geometry} material={nodes.modelobj.material} />
    </group>
  )
}

useGLTF.preload('https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/yellowPepper.glb')
