/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 PepperSauce.glb --types
*/

import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import * as THREE from "three";
import { Group } from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    Material1: THREE.Mesh;
    Material1001: THREE.Mesh;
    Material1002: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Mat.1"]: THREE.MeshPhysicalMaterial;
    ["Mat.2"]: THREE.MeshStandardMaterial;
    ["Mat.5"]: THREE.MeshStandardMaterial;
  };
};

export function PepperSauce(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null!);
  const { nodes, materials } = useGLTF(
    "https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/PepperSauce.glb",
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.002"]}
        position={[2.134, -58.219, 135.839] as const}
        scale={[139.699, 103.959, 139.032] as const}
      />
      <mesh
        geometry={nodes.Material1.geometry}
        material={materials["Mat.1"]}
        position={[0, -38.952, 0] as const}
        scale={[1.18, 1.15, 1.18] as const}
      />
      <mesh
        geometry={nodes.Material1001.geometry}
        material={materials["Mat.2"]}
        position={[0, 93.081, 0] as const}
        scale={[1.189, 1.296, 1.189] as const}
      />
      <mesh
        geometry={nodes.Material1002.geometry}
        material={materials["Mat.5"]}
        position={[0, 232.805, 0] as const}
        scale={[1.193, 1.155, 1.156] as const}
      />
    </group>
  );
}

useGLTF.preload(
  "https://sunnyisland.s3.us-east-2.amazonaws.com/media/glb/PepperSauce.glb",
);
